spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/${DATABASE_NAME}?characterEncoding=UTF8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: ${MYSQL_USER_NAME}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  profiles:
    active: dev
  application:
    name: ruijiTakeOut
  flyway:
    enabled: true
    encoding: UTF-8
    locations: classpath:db/migration
    sqlMigrationPrefix: V
    sqlMigrationSeparator: __
    validateOnMigrate: true
    baselineOnMigrate: true
  server:
    port: ${APPLICATION_PORT}
